# Generated by Django 5.0 on 2023-12-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BolgPage',
            new_name='BlogPage',
        ),
    ]
