# Generated by Django 5.0 on 2023-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Post date'),
        ),
    ]
