# Generated by Django 5.0 on 2023-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postpage_date_author_postpage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='author',
            new_name='authors',
        ),
    ]
