# Generated by Django 5.0 on 2023-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_name_case_insensitive',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
